# Generated by Django 4.2.7 on 2025-10-31 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_visitrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image_url',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
    ]
