# Generated by Django 6.0 on 2026-04-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='admin_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
