# Generated by Django 4.2.28 on 2026-04-13 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_contactmessage_admin_notes_contactmessage_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=1024),
        ),
    ]
